### ISSUE TITLE
state unit tests are failing

### ISSUE THREAD

**Issue by ailg** [fluffle/goirc#75]
```
$ go test github.com/fluffle/goirc/state/...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4934e6]

goroutine 41 [running]:
github.com/fluffle/goirc/state.TestSTRaces.func2(0xc820010680, 0xc8200a6be0, 0xc8200a6ca0, 0x1)
	github.com/fluffle/goirc/state/tracker_test.go:582 +0x106
created by github.com/fluffle/goirc/state.TestSTRaces
	github.com/fluffle/goirc/state/tracker_test.go:584 +0x41e
```

**Comment by fluffle** [comment]
Nuked them, sorry about that.
